services:
  my-nginx-service:
    image: nginx:latest
    container_name: nginx-service
    volumes:
     # logs
     - ./volumes/nginx/logs:/var/log/nginx/
    ports:
      - "8000:80"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./log:/var/log/nginx
      - ./config/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    ports:
      - "9080:9080"
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - "9100:9100"
