global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['exporter:9100']  # Имя контейнера node-exporter

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-service:80']  # Имя контейнера Nginx
