auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    enabled: true
    dir: /loki/wal

  chunk_idle_period: 5m
  chunk_retain_period: 30s

  lifecycler:
    ring:
      kvstore:
        store: inmemory  # Используем inmemory для одиночного режима
      replication_factor: 1  # Установите на 1

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false

compactor:
  working_directory: /loki/compactor
