global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-service:80']  # Используй порт 80, если он активен
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['exporter:9100']  # Порт для node-exporter
