server:
  http_listen_port: 9080

positions:
  filename: /var/log/nginx/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Убедитесь, что адрес соответствует вашему Loki

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginxlogs
          __path__: /var/log/nginx/*.log  # Убедитесь, что это соответствует вашим логам
